env:
  ELIXIR_ASSERT_TIMEOUT: 2000
  LANG: C.UTF-8

test_task:
  container:
    image: buildpack-deps:trusty

  env:
    PATH: "${CIRRUS_WORKING_DIR}/otp/bin:${PATH}"
    ELIXIRC_OPTS: "--warnings-as-errors"
    ERLC_OPTS: "+warning_as_errors"

  matrix:
    - env:
        OTP_RELEASE: OTP-22.1
        CHECK_REPRODUCIBLE: true
        CHECK_POSIX_COMPLIANT: true
        TEST_FORMATTED: true
    # - env:
    #     OTP_RELEASE: OTP-22.0
    # - env:
    #     OTP_RELEASE: OTP-21.3.8
    # - env:
    #     OTP_RELEASE: OTP-21.2
    # - env:
    #     OTP_RELEASE: OTP-21.1
    # - env:
    #     OTP_RELEASE: OTP-21.0
    # - env:
    #     OTP_RELEASE: maint
    #   allow_failures: true
    #   skip_notifications: true
    # - env:
    #     OTP_RELEASE: master
    #   allow_failures: true
    #   skip_notifications: true

  install_script:
    - wget -O otp.tar.gz https://repo.hex.pm/builds/otp/ubuntu-14.04/${OTP_RELEASE}.tar.gz
    - mkdir -p otp
    - tar zxf otp.tar.gz -C otp --strip-components=1
    - otp/Install -minimal $(pwd)/otp
    - rm -rf .git

  compile_script: make compile

  test_formatted_background_script: |
    if [ -n "$TEST_FORMATTED" ]; then
      make test_formatted
    fi

  # check_posix_compliant_background_script: |
  #   if [ -n "$CHECK_POSIX_COMPLIANT" ]; then
  #     apt update
  #     apt install -y shellcheck
  #     shellcheck -e SC2039,2086 bin/elixir && echo "bin/elixir is POSIX compliant"
  #     shellcheck bin/elixirc && echo "bin/elixirc is POSIX compliant"
  #     shellcheck bin/iex && echo "bin/iex is POSIX compliant"
  #   fi

  # test_erlang_background_script: make test_erlang
  # test_stdlib_background_script: make test_stdlib
  # test_ex_unit_background_script: make test_ex_unit
  # test_logger_background_script: make test_logger
  # test_mix_background_script: make test_mix
  # test_eex_background_script: make test_eex
  test_iex_background_script: make test_iex
  # dialyzer_background_script: dialyzer -pa lib/elixir/ebin --build_plt --output_plt elixir.plt --apps lib/elixir/ebin/elixir.beam lib/elixir/ebin/Elixir.Kernel.beam

  # check_reproducible_background_script: |
  #   if [ -n "$CHECK_REPRODUCIBLE" ]; then
  #     make check_reproducible
  #   fi

  wait_for_scripts_script:
    - sleep 60

# test_windows_task:
#   windows_container:
#     matrix:
#       - image: fertapric/elixir-ci:otp-win64-22.0
#         os_version: 2019
#       - image: fertapric/elixir-ci:otp-win64-21.0.1
#         os_version: 2019

#   test_script:
#     - rmdir /s /q .git
#     - make
#     - make --keep-going test_erlang test_elixir
