env:
  ELIXIR_ASSERT_TIMEOUT: 2000
  LANG: C.UTF-8
  CIRRUS_CLONE_DEPTH: 1

test_linux_task:
  name: Linux, ${OTP_RELEASE}, Ubuntu 14.04

  container:
    image: buildpack-deps:trusty
    cpu: 8
    memory: 1500Mi

  env:
    ELIXIRC_OPTS: "--warnings-as-errors"
    ERLC_OPTS: "+warning_as_errors"
    PATH: "${CIRRUS_WORKING_DIR}/otp/bin:${PATH}"

  matrix:
    - env:
        OTP_RELEASE: OTP-22.1
        CHECK_POSIX_COMPLIANT: true
        CHECK_REPRODUCIBLE: true
        TEST_FORMATTED: true
    - env:
        OTP_RELEASE: OTP-22.0
    - env:
        OTP_RELEASE: OTP-21.3.8
    - env:
        OTP_RELEASE: OTP-21.2
    - env:
        OTP_RELEASE: OTP-21.1
    - env:
        OTP_RELEASE: OTP-21.0
    - env:
        OTP_RELEASE: maint
      allow_failures: true
      skip_notifications: true
    - env:
        OTP_RELEASE: master
      allow_failures: true
      skip_notifications: true

  install_script:
    - wget -O otp.tar.gz https://repo.hex.pm/builds/otp/ubuntu-14.04/${OTP_RELEASE}.tar.gz
    - mkdir -p otp
    - tar zxf otp.tar.gz -C otp --strip-components=1
    - otp/Install -minimal ${CIRRUS_WORKING_DIR}/otp
    - rm -rf .git
    - make compile

  build_info_script: bin/elixir --version

  test_formatted_script: |
    if [ -n "$TEST_FORMATTED" ]; then
      make test_formatted && echo "All files found to be properly formatted."
    else
      echo "The format of the Elixir code is only checked in the last stable Erlang/OTP version."
    fi

  dialyzer_script: dialyzer -pa lib/elixir/ebin --build_plt --output_plt elixir.plt --apps lib/elixir/ebin/elixir.beam lib/elixir/ebin/Elixir.Kernel.beam

  test_erlang_script: make test_erlang

  test_elixir_script: make test_elixir

  check_posix_compliant_script: |
    if [ -n "$CHECK_POSIX_COMPLIANT" ]; then
      apt update
      apt install -y shellcheck
      shellcheck -e SC2039,2086 bin/elixir && echo "bin/elixir is POSIX compliant"
      shellcheck bin/elixirc && echo "bin/elixirc is POSIX compliant"
      shellcheck bin/iex && echo "bin/iex is POSIX compliant"
    else
      echo "The format of the shell scripts is only checked in the last stable Erlang/OTP version."
    fi

  check_reproducible_script: |
    if [ -n "$CHECK_REPRODUCIBLE" ]; then
      make check_reproducible
    else
      echo "The format reproducibility of the build is only checked in the last stable Erlang/OTP version."
    fi

test_windows_task:
  name: Windows, OTP-${OTP_RELEASE}, Windows Server 2019

  matrix:
    - env:
        OTP_RELEASE: 22.0
        OS_VERSION: 2019

    - env:
        OTP_RELEASE: 21.0.1
        OS_VERSION: 2019

  windows_container:
    image: fertapric/elixir-ci:otp-win64-${OTP_RELEASE}
    os_version: ${OS_VERSION}
    cpu: 8
    memory: 1500Mi

  install_script:
    - rmdir /s /q .git
    - make compile

  build_info_script: bin/elixir --version

  test_erlang_script: make --keep-going test_erlang

  test_elixir_script: make --keep-going test_elixir
