language: bash
sudo: false

env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
    - LATEST_OTP_RELEASE=false
  matrix:
    - OTP_RELEASE=OTP-20.0
    - OTP_RELEASE=OTP-20.1
    - OTP_RELEASE=OTP-20.2
    - OTP_RELEASE=OTP-20.3
    - OTP_RELEASE=OTP-21.0
    - OTP_RELEASE=OTP-21.1
    - OTP_RELEASE=OTP-21.2 LATEST_OTP_RELEASE=true
    - OTP_RELEASE=maint
    - OTP_RELEASE=master

matrix:
  fast_finish: true
  allow_failures:
    - env: OTP_RELEASE=maint
    - env: OTP_RELEASE=master

install:
  - wget -O otp.tar.gz https://repo.hex.pm/builds/otp/ubuntu-14.04/${OTP_RELEASE}.tar.gz
  - mkdir -p otp
  - tar zxf otp.tar.gz -C otp --strip-components=1
  - otp/Install -minimal $(pwd)/otp
  - PATH=$(pwd)/otp/bin:$PATH

script:
  - rm -rf .git
  - ELIXIRC_OPTS="--warnings-as-errors" ERLC_OPTS="+warning_as_errors" make compile
  - make test
  - dialyzer -pa lib/elixir/ebin --build_plt --output_plt elixir.plt --apps lib/elixir/ebin/elixir.beam lib/elixir/ebin/Elixir.Kernel.beam

  # Check for reproducible builds only in the latest OTP release
  - |
    if [ "${LATEST_OTP_RELEASE}" == true ]; then
      make check_reproducible
    fi;

notifications:
  recipients:
    - jose.valim@gmail.com
    - eric.meadows.jonsson@gmail.com
    - lexmag@me.com
    - an.leopardi@gmail.com
